import pandas as pd

facttab = pd.read_csv("facttab.csv", sep=";")
custtab = pd.read_csv("customer.csv", sep=";", usecols=["CSID", "custid", "name"])

# merge customer and fact table and only get relevant columns
joinFactCust = pd.merge(left=facttab, right=custtab, on="CSID")[["CSID", "custid", "name", "price", "quantity"]]
# compute revenue generated by each order position
joinFactCust["revenue"] = joinFactCust["price"] * joinFactCust["quantity"]
# print(joinFactCust)

# Aggregate revenue for each customer
revenueByCust = joinFactCust[["CSID", "custid", "name", "revenue"]].groupby(["CSID", "custid", "name"]).sum()
# sort by revenue
revenueByCust.sort_values("revenue", ascending=False, inplace=True)
# print top 3 customers
print(revenueByCust[:3])
